export const INITIAL_LOAD_INIT = '@ordersFPR/INITIAL_LOAD_INIT';
export const INITIAL_LOAD_SUCCESS = '@ordersFPR/INITIAL_LOAD_SUCCESS';
export const INITIAL_LOAD_FAILURE = '@ordersFPR/INITIAL_LOAD_FAILURE';

export const GET_ALL_PRODUCTEDITIONS_INIT =
  '@ordersFPR/GET_ALL_PRODUCTEDITIONS_INIT';
export const GET_ALL_PRODUCTEDITIONS_SUCESS =
  '@ordersFPR/GET_ALL_PRODUCTEDITIONS_SUCESS';
export const GET_ALL_PRODUCTEDITIONS_FAILURE =
  '@ordersFPR/GET_ALL_PRODUCTEDITIONS_FAILURE';

export const FILTER_ORDERSFPR_INIT = '@ordersFPR/FILTER_ORDERSFPR_INIT';
export const FILTER_ORDERSFPR_SUCCESS = '@ordersFPR/FILTER_ORDERSFPR_SUCCESS';
export const FILTER_ORDERSFPR_FAILURE = '@ordersFPR/FILTER_ORDERSFPR_FAILURE';

export const ADD_ORDERSFPR_INIT = '@ordersFPR/ADD_ORDERSFPR_INIT';
export const ADD_ORDERSFPR_SUCCESS = '@ordersFPR/ADD_ORDERSFPR_SUCCESS';
export const ADD_ORDERSFPR_FAILURE = '@ordersFPR/ADD_ORDERSFPR_FAILURE';

export const CLEARFILTERS = '@ordersFPR/CLEARFILTERS';
