version: '3.3'

services:

  ladevi_ventas_front:
    image: ladevi_ventas_front
    container_name: "ladevi_ventas_front"
    build:
      context: .
      dockerfile: Dockerfile.react
    ports:
      - "8080:80"
    environment:
      x: a
    env_file: .env
    restart: unless-stopped
    command: ["nginx", "-g", "daemon off;"]
