export const ACCOUNTING_FIELDS_INITIAL_LOAD_INIT =
  "@accountingFields/ACCOUNTING_FIELDS_INITIAL_LOAD_INIT";
export const ACCOUNTING_FIELDS_INITIAL_LOAD_SUCCESS =
  "@accountingFields/ACCOUNTING_FIELDS_INITIAL_LOAD_SUCCESS";
export const ACCOUNTING_FIELDS_INITIAL_LOAD_FAILURE =
  "@accountingFields/ACCOUNTING_FIELDS_INITIAL_LOAD_FAILURE";

export const GET_ALL_ACCOUNTING_FIELDS_INIT =
  "@accountingFields/GET_ALL_ACCOUNTING_FIELDS_INIT";
export const GET_ALL_ACCOUNTING_FIELDS_SUCCESS =
  "@accountingFields/GET_ALL_ACCOUNTING_FIELDS_SUCCESS";
export const GET_ALL_ACCOUNTING_FIELDS_FAILURE =
  "@accountingFields/GET_ALL_ACCOUNTING_FIELDS_FAILURE";

export const FILTER_ACCOUNTING_FIELDS_INIT =
  "@accountingFields/FILTER_ACCOUNTING_FIELDS_INIT";
export const FILTER_ACCOUNTING_FIELDS_SUCCESS =
  "@accountingFields/FILTER_ACCOUNTING_FIELDS_SUCCESS";
export const FILTER_ACCOUNTING_FIELDS_FAILURE =
  "@accountingFields/FILTER_ACCOUNTING_FIELDS_FAILURE";

export const ADD_ACCOUNTING_FIELD_INIT =
  "@accountingFields/ADD_ACCOUNTING_FIELD_INIT";
export const ADD_ACCOUNTING_FIELD_SUCCESS =
  "@accountingFields/ADD_ACCOUNTING_FIELD_SUCCESS";
export const ADD_ACCOUNTING_FIELD_FAILURE =
  "@accountingFields/ADD_ACCOUNTING_FIELD_FAILURE";

export const EDIT_ACCOUNTING_FIELD_INIT =
  "@accountingFields/EDIT_ACCOUNTING_FIELD_INIT";
export const EDIT_ACCOUNTING_FIELD_SUCCESS =
  "@accountingFields/EDIT_ACCOUNTING_FIELD_SUCCESS";
export const EDIT_ACCOUNTING_FIELD_FAILURE =
  "@accountingFields/EDIT_ACCOUNTING_FIELD_FAILURE";

export const DELETE_ACCOUNTING_FIELD_INIT =
  "@accountingFields/DELETE_ACCOUNTING_FIELD_INIT";
export const DELETE_ACCOUNTING_FIELD_SUCCESS =
  "@accountingFields/DELETE_ACCOUNTING_FIELD_SUCCESS";
export const DELETE_ACCOUNTING_FIELD_FAILURE =
  "@accountingFields/DELETE_ACCOUNTING_FIELD_FAILURE";

export const ACCOUNTING_FIELDS_SHOW_ADD_MODAL =
  "@accountingFields/SHOW_ADD_MODAL";
export const ACCOUNTING_FIELDS_SHOW_EDIT_MODAL =
  "@accountingFields/SHOW_EDIT_MODAL";
export const ACCOUNTING_FIELDS_SHOW_DELETE_MODAL =
  "@accountingFields/SHOW_DELETE_MODAL";
