// Obtener productos
export const FETCH_PRODUCTS_INIT = '@production/FETCH_PRODUCTS_INIT';
export const FETCH_PRODUCTS_SUCCESS = '@production/FETCH_PRODUCTS_SUCCESS';
export const FETCH_PRODUCTS_FAILURE = '@production/FETCH_PRODUCTS_FAILURE';

// Obtener ediciones
export const FETCH_EDITIONS_INIT = '@production/FETCH_EDITIONS_INIT';
export const FETCH_EDITIONS_SUCCESS = '@production/FETCH_EDITIONS_SUCCESS';
export const FETCH_EDITIONS_FAILURE = '@production/FETCH_EDITIONS_FAILURE';

export const SET_SELECTED_PRODUCT = '@production/SET_SELECTED_PRODUCT';
export const SET_SELECTED_EDITION = '@production/SET_SELECTED_EDITION';

// Obtener production templates
export const FETCH_PRODUCTION_TEMPLATES_INIT =
  '@production/FETCH_PRODUCTION_TEMPLATES_INIT';
export const FETCH_PRODUCTION_TEMPLATES_SUCCESS =
  '@production/FETCH_PRODUCTION_TEMPLATES_SUCCESS';
export const FETCH_PRODUCTION_TEMPLATES_FAILURE =
  '@production/FETCH_PRODUCTION_TEMPLATES_FAILURE';

// Agregar slot
export const ADD_SLOT_INIT = '@production/ADD_SLOT_INIT';
export const ADD_SLOT_SUCCESS = '@production/ADD_SLOT_SUCCESS';
export const ADD_SLOT_FAILURE = '@production/ADD_SLOT_FAILURE';

// Remover slot
export const REMOVE_SLOT_INIT = '@production/REMOVE_SLOT_INIT';
export const REMOVE_SLOT_SUCCESS = '@production/REMOVE_SLOT_SUCCESS';
export const REMOVE_SLOT_FAILURE = '@production/REMOVE_SLOT_FAILURE';

// Actualizar observación
export const UPDATE_OBSERVATION_INIT = '@production/UPDATE_OBSERVATION_INIT';
export const UPDATE_OBSERVATION_SUCCESS =
  '@production/UPDATE_OBSERVATION_SUCCESS';
export const UPDATE_OBSERVATION_FAILURE =
  '@production/UPDATE_OBSERVATION_FAILURE';

// Marcar como editorial
export const MARK_AS_EDITORIAL_INIT = '@production/MARK_AS_EDITORIAL_INIT';
export const MARK_AS_EDITORIAL_SUCCESS =
  '@production/MARK_AS_EDITORIAL_SUCCESS';
export const MARK_AS_EDITORIAL_FAILURE =
  '@production/MARK_AS_EDITORIAL_FAILURE';

// Marcar como CA
export const MARK_AS_CA_INIT = '@production/MARK_AS_CA_INIT';
export const MARK_AS_CA_SUCCESS = '@production/MARK_AS_CA_SUCCESS';
export const MARK_AS_CA_FAILURE = '@production/MARK_AS_CA_FAILURE';

// Mover publicaciones entre slots
export const MOVE_PUBLISHING_ORDER_BETWEEN_SLOTS_INIT =
  '@production/MOVE_PUBLISHING_ORDER_BETWEEN_SLOTS_INIT';
export const MOVE_PUBLISHING_ORDER_BETWEEN_SLOTS_SUCCESS =
  '@production/MOVE_PUBLISHING_ORDER_BETWEEN_SLOTS_SUCCESS';
export const MOVE_PUBLISHING_ORDER_BETWEEN_SLOTS_FAILURE =
  '@production/MOVE_PUBLISHING_ORDER_BETWEEN_SLOTS_FAILURE';

// Validaciones
export const VALIDATE_PAGE_REDUCTION_INIT =
  '@production/VALIDATE_PAGE_REDUCTION_INIT';
export const VALIDATE_PAGE_REDUCTION_SUCCESS =
  '@production/VALIDATE_PAGE_REDUCTION_SUCCESS';
export const VALIDATE_PAGE_REDUCTION_FAILURE =
  '@production/VALIDATE_PAGE_REDUCTION_FAILURE';

export const VALIDATE_INVENTORY_REDUCTION_INIT =
  '@production/VALIDATE_INVENTORY_REDUCTION_INIT';
export const VALIDATE_INVENTORY_REDUCTION_SUCCESS =
  '@production/VALIDATE_INVENTORY_REDUCTION_SUCCESS';
export const VALIDATE_INVENTORY_REDUCTION_FAILURE =
  '@production/VALIDATE_INVENTORY_REDUCTION_FAILURE';
