version: '3.8'
services:
  test-db:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sa -d ladevi_ventas_test"]
      interval: 10s
      timeout: 5s
      retries: 5

  test-api:
    build:
      context: ../../ladevi-ventas-api
      dockerfile: Dockerfile.test
    environment:
      - ASPNETCORE_ENVIRONMENT=Testing
      - ASPNETCORE_URLS=http://+:80
      - DefaultConnection=Server=test-db;Database=ladevi_ventas_test;User Id=sa;Password=test123;Port=5432;
      # - EnableTestingEndpoints=true
      - IntegrationTestSeedToken=tfENXZ840DEO7GKVPQi3
    ports:
      - "5003:80"
    depends_on:
      test-db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s