export const SET_LOGGED_USER = "@appData/SET_LOGGED_USER";

export const FETCH_APP_ROLES_INIT = "@appData/FETCH_APP_ROLES_INIT";
export const FETCH_APP_ROLES_SUCCESS = "@appData/FETCH_APP_ROLES_SUCCESS";
export const FETCH_APP_ROLES_FAILURE = "@appData/FETCH_APP_ROLES_FAILURE";

export const FETCH_COUNTRIES_INIT = "@appData/FETCH_COUNTRIES_INIT";
export const FETCH_COUNTRIES_SUCCESS = "@appData/FETCH_COUNTRIES_SUCCESS";
export const FETCH_COUNTRIES_FAILURE = "@appData/FETCH_COUNTRIES_FAILURE";

export const FETCH_STATES_INIT = "@appData/FETCH_STATES_INIT";
export const FETCH_STATES_SUCCESS = "@appData/FETCH_STATES_SUCCESS";
export const FETCH_STATES_FAILURE = "@appData/FETCH_STATES_FAILURE";

export const FETCH_DISTRICTS_INIT = "@appData/FETCH_DISTRICTS_INIT";
export const FETCH_DISTRICTS_SUCCESS = "@appData/FETCH_DISTRICTS_SUCCESS";
export const FETCH_DISTRICTS_FAILURE = "@appData/FETCH_DISTRICTS_FAILURE";

export const FETCH_CITIES_INIT = "@appData/FETCH_CITIES_INIT";
export const FETCH_CITIES_SUCCESS = "@appData/FETCH_CITIES_SUCCESS";
export const FETCH_CITIES_FAILURE = "@appData/FETCH_CITIES_FAILURE";
