export const CONSTANTS = {
  ARGENTINA_COUNTRY_ID: 4,
  PANAMA_COUNTRY_ID: 54,
  USA_COUNTRY_ID: 81,
  USA_CURRENCY_ID: 2,
  EUR_CURRENCY_ID: -1,
  CONSUMIDOR_FINAL_TAX_CATEGORY_CODE: "CF",
  CUIT_TAX_TYPE_ID: 2,
};
