export const GET_ALL_PRODUCTS_INIT = '@products/GET_ALL_PRODUCTS_INIT';
export const GET_ALL_PRODUCTS_SUCCESS = '@products/GET_ALL_PRODUCTS_SUCCESS';
export const GET_ALL_PRODUCTS_FAILURE = '@products/GET_ALL_PRODUCTS_FAILURE';

export const FILTER_PRODUCTS_INIT = '@products/FILTER_PRODUCTS_INIT';
export const FILTER_PRODUCTS_SUCCESS = '@products/FILTER_PRODUCTS_SUCCESS';
export const FILTER_PRODUCTS_FAILURE = '@products/FILTER_PRODUCTS_FAILURE';

export const ADD_PRODUCT_INIT = '@products/ADD_PRODUCT_INIT';
export const ADD_PRODUCT_SUCCESS = '@products/ADD_PRODUCT_SUCCESS';
export const ADD_PRODUCT_FAILURE = '@products/ADD_PRODUCT_FAILURE';

export const EDIT_PRODUCT_INIT = '@products/EDIT_PRODUCT_INIT';
export const EDIT_PRODUCT_SUCCESS = '@products/EDIT_PRODUCT_SUCCESS';
export const EDIT_PRODUCT_FAILURE = '@products/EDIT_PRODUCT_FAILURE';

export const DELETE_PRODUCT_INIT = '@products/DELETE_PRODUCT_INIT';
export const DELETE_PRODUCT_SUCCESS = '@products/DELETE_PRODUCT_SUCCESS';
export const DELETE_PRODUCT_FAILURE = '@products/DELETE_PRODUCT_FAILURE';

export const GET_ALL_PRODUCT_TYPES_INIT =
  '@products/GET_ALL_PRODUCT_TYPES_INIT';
export const GET_ALL_PRODUCT_TYPES_SUCCESS =
  '@products/GET_ALL_PRODUCT_TYPES_SUCCESS';
export const GET_ALL_PRODUCT_TYPES_FAILURE =
  '@products/GET_ALL_PRODUCT_TYPES_FAILURE';

export const PRODUCTS_INITIAL_LOAD_INIT =
  '@products/PRODUCTS_INITIAL_LOAD_INIT';
export const PRODUCTS_INITIAL_LOAD_SUCCESS =
  '@products/PRODUCTS_INITIAL_LOAD_SUCCESS';
export const PRODUCTS_INITIAL_LOAD_FAILURE =
  '@products/PRODUCTS_INITIAL_LOAD_FAILURE';

export const PRODUCT_SHOW_ADD_MODAL = '@products/SHOW_ADD_MODAL';
export const PRODUCT_SHOW_EDIT_MODAL = '@products/SHOW_EDIT_MODAL';
export const PRODUCT_SHOW_DELETE_MODAL = '@products/SHOW_DELETE_MODAL';
