export const INITIAL_LOAD_INIT = '@ordersByClient/INITIAL_LOAD_INIT';
export const INITIAL_LOAD_SUCCESS = '@ordersByClient/INITIAL_LOAD_SUCCESS';
export const INITIAL_LOAD_FAILURE = '@ordersByClient/INITIAL_LOAD_FAILURE';

export const FILTER_ORDERSBYCLIENT_INIT =
  '@ordersByClient/FILTER_ORDERSBYCLIENT_INIT';
export const FILTER_ORDERSBYCLIENT_SUCCESS =
  '@ordersByClient/FILTER_ORDERSBYCLIENT_SUCCESS';
export const FILTER_ORDERSBYCLIENT_FAILURE =
  '@ordersByClient/FILTER_ORDERSBYCLIENT_FAILURE';

export const GET_PRODUCT_BYTYPE_INIT =
  '@ordersByClient/GET_PRODUCT_BYTYPE_INIT';
export const GET_PRODUCT_BYTYPE_SUCCESS =
  '@ordersByClient/GET_PRODUCT_BYTYPE_SUCCESS';
export const GET_PRODUCT_BYTYPE_FAILURE =
  '@ordersByClient/GET_PRODUCT_BYTYPE_FAILURE';

export const GET_PRODUCTEDITION_BYPRODUCT_INIT =
  '@ordersByClient/GET_PRODUCTEDITION_BYPRODUCT_INIT';
export const GET_PRODUCTEDITION_BYPRODUCT_SUCCESS =
  '@ordersByClient/GET_PRODUCTEDITION_BYPRODUCT_SUCCESS';
export const GET_PRODUCTEDITION_BYPRODUCT_FAILURE =
  '@ordersByClient/GET_PRODUCTEDITION_BYPRODUCT_FAILURE';

export const CLEARFILTERS = '@ordersByClient/CLEARFILTERS';
