export const INITIAL_LOAD_INIT = "@ordersBySeller/INITIAL_LOAD_INIT";
export const INITIAL_LOAD_SUCCESS = "@ordersBySeller/INITIAL_LOAD_SUCCESS";
export const INITIAL_LOAD_FAILURE = "@ordersBySeller/INITIAL_LOAD_FAILURE";

export const FILTER_ORDERSBYSELLER_INIT =
  "@ordersBySeller/FILTER_ORDERSFPR_INIT";
export const FILTER_ORDERSBYSELLER_SUCCESS =
  "@ordersBySeller/FILTER_ORDERSFPR_SUCCESS";
export const FILTER_ORDERSBYSELLER_FAILURE =
  "@ordersBySeller/FILTER_ORDERSFPR_FAILURE";

export const GET_PRODUCT_BYTYPE_INIT =
  "@ordersBySeller/GET_PRODUCT_BYTYPE_INIT";
export const GET_PRODUCT_BYTYPE_SUCCESS =
  "@ordersBySeller/GET_PRODUCT_BYTYPE_SUCCESS";
export const GET_PRODUCT_BYTYPE_FAILURE =
  "@ordersBySeller/GET_PRODUCT_BYTYPE_FAILURE";

export const GET_PRODUCTEDITION_BYPRODUCT_INIT =
  "@ordersBySeller/GET_PRODUCTEDITION_BYPRODUCT_INIT";
export const GET_PRODUCTEDITION_BYPRODUCT_SUCCESS =
  "@ordersBySeller/GET_PRODUCTEDITION_BYPRODUCT_SUCCESS";
export const GET_PRODUCTEDITION_BYPRODUCT_FAILURE =
  "@ordersBySeller/GET_PRODUCTEDITION_BYPRODUCT_FAILURE";

export const CLEARFILTERS = "@ordersBySeller/CLEARFILTERS";
