export const GET_ALL_CONTRACTS_INIT = "@contracts/GET_ALL_CONTRACTS_INIT";
export const GET_ALL_CONTRACTS_SUCCESS = "@contracts/GET_ALL_CONTRACTS_SUCCESS";
export const GET_ALL_CONTRACTS_FAILURE = "@contracts/GET_ALL_CONTRACTS_FAILURE";

export const INITIAL_LOAD_INIT = "@contracts/INITIAL_LOAD_INIT";
export const INITIAL_LOAD_SUCCESS = "@contracts/INITIAL_LOAD_SUCCESS";
export const INITIAL_LOAD_FAILURE = "@contracts/INITIAL_LOAD_FAILURE";

export const SEARCH_CONTRACTS_INIT = "@contracts/SEARCH_CONTRACTS_INIT";
export const SEARCH_CONTRACTS_SUCCESS = "@contracts/SEARCH_CONTRACTS_SUCCESS";
export const SEARCH_CONTRACTS_FAILURE = "@contracts/SEARCH_CONTRACTS_FAILURE";

export const SHOW_ADD_MODAL = "@contracts/SHOW_ADD_MODAL";
export const SHOW_EDIT_MODAL = "@contracts/SHOW_EDIT_MODAL";
export const SHOW_DELETE_MODAL = "@contracts/SHOW_DELETE_MODAL";

export const ADD_CONTRACT_INIT = "@contracts/ADD_CONTRACT_INIT";
export const ADD_CONTRACT_SUCCESS = "@contracts/ADD_CONTRACT_SUCCESS";
export const ADD_CONTRACT_FAILURE = "@contracts/ADD_CONTRACT_FAILURE";

export const EDIT_CONTRACT_INIT = "@contracts/EDIT_CONTRACT_INIT";
export const EDIT_CONTRACT_SUCCESS = "@contracts/EDIT_CONTRACT_SUCCESS";
export const EDIT_CONTRACT_FAILURE = "@contracts/EDIT_CONTRACT_FAILURE";

export const DELETE_CONTRACT_INIT = "@contracts/DELETE_CONTRACT_INIT";
export const DELETE_CONTRACT_SUCCESS = "@contracts/DELETE_CONTRACT_SUCCESS";
export const DELETE_CONTRACT_FAILURE = "@contracts/DELETE_CONTRACT_FAILURE";

export const FILTER_CONTRACTS_INIT = "@contracts/FILTER_CONTRACTS_INIT";
export const FILTER_CONTRACTS_SUCCESS = "@contracts/FILTER_CONTRACTS_SUCCESS";
export const FILTER_CONTRACTS_FAILURE = "@contracts/FILTER_CONTRACTS_FAILURE";

export const GET_SPACETYPES_INIT = "@contracts/GET_SPACETYPES_INIT";
export const GET_SPACETYPES_SUCCESS = "@contracts/GET_SPACETYPES_SUCCESS";
export const GET_SPACETYPES_FAILURE = "@contracts/GET_SPACETYPES_FAILURE";

export const GET_CURRENCIES_INIT = "@contracts/GET_CURRENCIES_INIT";
export const GET_CURRENCIES_SUCCESS = "@contracts/GET_CURRENCIES_SUCCESS";
export const GET_CURRENCIES_FAILURE = "@contracts/GET_CURRENCIES_FAILURE";

export const GET_EUROPARITY_INIT = "@contracts/GET_EUROPARITY_INIT";
export const GET_EUROPARITY_SUCCESS = "@contracts/GET_EUROPARITY_SUCCESS";
export const GET_EUROPARITY_FAILURE = "@contracts/GET_EUROPARITY_FAILURE";
