export const LOGIN_INIT = "@login/LOGIN_INIT";
export const LOGIN_SUCCESS = "@login/LOGIN_SUCCESS";
export const LOGIN_FAILURE = "@login/LOGIN_FAILURE";

export const FORGOT_PASSWORD_INIT = "@login/FORGOT_PASSWORD_INIT";
export const FORGOT_PASSWORD_SUCCESS = "@login/FORGOT_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_FAILURE = "@login/FORGOT_PASSWORD_FAILURE";

export const LOGOUT_INIT = "@login/LOGOUT_INIT";
export const LOGOUT_SUCCESS = "@login/LOGOUT_SUCCESS";

export const RESET_PASSWORD_INIT = "@login/RESET_PASSWORD_INIT";
export const RESET_PASSWORD_SUCCESS = "@login/RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_FAILURE = "@login/RESET_PASSWORD_FAILURE";

export const CONFIRM_USER_INIT = "@login/CONFIRM_USER_INIT";
export const CONFIRM_USER_SUCCESS = "@login/CONFIRM_USER_SUCCESS";
export const CONFIRM_USER_FAILURE = "@login/CONFIRM_USER_FAILURE";
