import React from "react";
import Modal from "shared/components/Modal";
import ContractForm from "./Contract";

export default props => (
  <>
    <Modal
      shouldClose={true}
      closeHandler={props.actions.showAddModal}
      isOpen={props.showAddModal}
    >
      <ContractForm
        selectedItem={{}}
        addMode={true}
        availableSalesmens={props.availableSalesmens}
        availableProducts={props.availableProducts}
        availableSpaceTypes={props.availableSpaceTypes}
        availableSpaceLocations={props.availableSpaceLocations}
        availableClients={props.availableClients}
        availableCountries={props.availableCountries}
        saveHandler={props.actions.addContract}
        closeHandler={props.actions.showAddModal}
        getSpaceTypesByProduct={props.actions.getSpaceTypesByProduct}
        userLogueado={props.userLogueado}
        getProductEditionsHandler={props.actions.getProductEditions}
        availableEditions={props.availableEditions}
        errors={props.errors}
        getSpaceTypesAvailable={props.actions.getSpaceTypesAvailable}
        getSpaceLocationsAvailable={props.actions.getSpaceLocationsAvailable}
        availableSpaceLocationsForOrder={props.availableSpaceLocationsForOrder}
        availableSpaceTypesForOrder={props.availableSpaceTypesForOrder}
        addOrderHandler={props.actions.addOrder}
        availableCurrencies={props.availableCurrencies}
        availableEuroParities={props.availableEuroParities}
        getCurrenciesByCountryHandler={props.actions.getCurrenciesByCountry}
        filtros={props.filters}
        loading={props.loading}
        formikPropsDuplicate={props.formikPropsDuplicate}
        formikPropsDuplicateHandler={props.setFormikPropsDuplicate}
      />
    </Modal>
    <Modal
      shouldClose={true}
      closeHandler={props.actions.showEditModal}
      isOpen={props.showEditModal}
    >
      <ContractForm
        selectedItem={props.selectedItem}
        editMode={true}
        availableSalesmens={props.availableSalesmens}
        availableProducts={props.availableProducts}
        availableSpaceTypes={props.availableSpaceTypes}
        availableSpaceLocations={props.availableSpaceLocations}
        availableClients={props.availableClients}
        availableCountries={props.availableCountries}
        saveHandler={props.actions.editContract}
        closeHandler={props.actions.showEditModal}
        userLogueado={props.userLogueado}
        getSpaceTypesByProduct={props.actions.getSpaceTypesByProduct}
        getProductEditionsHandler={props.actions.getProductEditions}
        availableEditions={props.availableEditions}
        errors={props.errors}
        getSpaceTypesAvailable={props.actions.getSpaceTypesAvailable}
        getSpaceLocationsAvailable={props.actions.getSpaceLocationsAvailable}
        availableSpaceLocationsForOrder={props.availableSpaceLocationsForOrder}
        availableSpaceTypesForOrder={props.availableSpaceTypesForOrder}
        addOrderHandler={props.actions.addOrder}
        editOrderHandler={props.actions.editOrder}
        deleteOrderHandler={props.actions.deleteOrder}
        availableCurrencies={props.availableCurrencies}
        availableEuroParities={props.availableEuroParities}
        getCurrenciesByCountryHandler={props.actions.getCurrenciesByCountry}
        getClientsWithBalance={props.actions.getClientsWithBalance}
        filtros={props.filters}
        loading={props.loading}
        duplicateContractHandler={props.duplicateContractHandler}
        formikPropsDuplicate={props.formikPropsDuplicate}
        formikPropsDuplicateHandler={props.setFormikPropsDuplicate}
      />
    </Modal>
    <Modal
      shouldClose={true}
      closeHandler={props.actions.showDeleteModal}
      isOpen={props.showDeleteModal}
    >
      <ContractForm
        selectedItem={props.selectedItem}
        deleteMode={true}
        availableSalesmens={props.availableSalesmens}
        availableProducts={props.availableProducts}
        availableSpaceTypes={props.availableSpaceTypes}
        availableSpaceLocations={props.availableSpaceLocations}
        availableClients={props.availableClients}
        availableCountries={props.availableCountries}
        saveHandler={props.actions.deleteContract}
        errors={props.errors}
        closeHandler={props.actions.showDeleteModal}
        userLogueado={props.userLogueado}
        availableCurrencies={props.availableCurrencies}
        availableEuroParities={props.availableEuroParities}
        getCurrenciesByCountryHandler={props.actions.getCurrenciesByCountry}
        loading={props.loading}
      />
    </Modal>
  </>
);
