export const GET_ALL_PRODUCT_ADVERTISING_SPACES_INIT =
  '@advertisingSpaces/GET_ALL_PRODUCT_ADVERTISING_SPACES_INIT';
export const GET_ALL_PRODUCT_ADVERTISING_SPACES_SUCCESS =
  '@advertisingSpaces/GET_ALL_PRODUCT_ADVERTISING_SPACES_SUCCESS';
export const GET_ALL_PRODUCT_ADVERTISING_SPACES_FAILURE =
  '@advertisingSpaces/GET_ALL_PRODUCT_ADVERTISING_SPACES_FAILURE';

export const ADD_PRODUCT_ADVERTISING_SPACE_INIT =
  '@advertisingSpaces/ADD_PRODUCT_ADVERTISING_SPACE_INIT';
export const ADD_PRODUCT_ADVERTISING_SPACE_SUCCESS =
  '@advertisingSpaces/ADD_PRODUCT_ADVERTISING_SPACE_SUCCESS';
export const ADD_PRODUCT_ADVERTISING_SPACE_FAILURE =
  '@advertisingSpaces/ADD_PRODUCT_ADVERTISING_SPACE_FAILURE';

export const EDIT_PRODUCT_ADVERTISING_SPACE_INIT =
  '@advertisingSpaces/EDIT_PRODUCT_ADVERTISING_SPACE_INIT';
export const EDIT_PRODUCT_ADVERTISING_SPACE_SUCCESS =
  '@advertisingSpaces/EDIT_PRODUCT_ADVERTISING_SPACE_SUCCESS';
export const EDIT_PRODUCT_ADVERTISING_SPACE_FAILURE =
  '@advertisingSpaces/EDIT_PRODUCT_ADVERTISING_SPACE_FAILURE';

export const DELETE_PRODUCT_ADVERTISING_SPACE_INIT =
  '@advertisingSpaces/DELETE_PRODUCT_ADVERTISING_SPACE_INIT';
export const DELETE_PRODUCT_ADVERTISING_SPACE_SUCCESS =
  '@advertisingSpaces/DELETE_PRODUCT_ADVERTISING_SPACE_SUCCESS';
export const DELETE_PRODUCT_ADVERTISING_SPACE_FAILURE =
  '@advertisingSpaces/DELETE_PRODUCT_ADVERTISING_SPACE_FAILURE';

export const PRODUCT_ADVERTISING_SPACE_SHOW_ADD_MODAL =
  '@advertisingSpaces/SHOW_ADD_MODAL';
export const PRODUCT_ADVERTISING_SPACE_SHOW_EDIT_MODAL =
  '@advertisingSpaces/SHOW_EDIT_MODAL';
export const PRODUCT_ADVERTISING_SPACE_SHOW_DELETE_MODAL =
  '@advertisingSpaces/SHOW_DELETE_MODAL';

export const PRODUCT_ADVERTISING_SPACE_INITIAL_LOAD_INIT =
  '@advertisingSpaces/PRODUCT_ADVERTISING_SPACE_INITIAL_LOAD_INIT';
export const PRODUCT_ADVERTISING_SPACE_INITIAL_LOAD_SUCCESS =
  '@advertisingSpaces/PRODUCT_ADVERTISING_SPACE_INITIAL_LOAD_SUCCESS';
export const PRODUCT_ADVERTISING_SPACE_INITIAL_LOAD_FAILURE =
  '@advertisingSpaces/PRODUCT_ADVERTISING_SPACE_INITIAL_LOAD_FAILURE';

export const FILTER_PRODUCT_ADVERTISING_SPACES_INIT =
  '@advertisingSpaces/FILTER_PRODUCT_ADVERTISING_SPACES_INIT';
export const FILTER_PRODUCT_ADVERTISING_SPACES_SUCCESS =
  '@advertisingSpaces/FILTER_PRODUCT_ADVERTISING_SPACES_SUCCESS';
export const FILTER_PRODUCT_ADVERTISING_SPACES_FAILURE =
  '@advertisingSpaces/FILTER_PRODUCT_ADVERTISING_SPACES_FAILURE';
