export const EDITIONS_INITIAL_LOAD_INIT =
  "@editions/EDITIONS_INITIAL_LOAD_INIT";
export const EDITIONS_INITIAL_LOAD_SUCCESS =
  "@editions/EDITIONS_INITIAL_LOAD_SUCCESS";
export const EDITIONS_INITIAL_LOAD_FAILURE =
  "@editions/EDITIONS_INITIAL_LOAD_FAILURE";

export const GET_ALL_EDITIONS_INIT = "@editions/GET_ALL_EDITIONS_INIT";
export const GET_ALL_EDITIONS_SUCCESS = "@editions/GET_ALL_EDITIONS_SUCCESS";
export const GET_ALL_EDITIONS_FAILURE = "@editions/GET_ALL_EDITIONS_FAILURE";

export const ADD_EDITION_INIT = "@editions/ADD_EDITION_INIT";
export const ADD_EDITION_SUCCESS = "@editions/ADD_EDITION_SUCCESS";
export const ADD_EDITION_FAILURE = "@editions/ADD_EDITION_FAILURE";

export const EDIT_EDITION_INIT = "@editions/EDIT_EDITION_INIT";
export const EDIT_EDITION_SUCCESS = "@editions/EDIT_EDITION_SUCCESS";
export const EDIT_EDITION_FAILURE = "@admin/EDIT_EDITION_FAILURE";

export const DELETE_EDITION_INIT = "@editions/DELETE_EDITION_INIT";
export const DELETE_EDITION_SUCCESS = "@editions/DELETE_EDITION_SUCCESS";
export const DELETE_EDITION_FAILURE = "@editions/DELETE_EDITION_FAILURE";

export const EDITIONS_SHOW_ADD_MODAL = "@editions/SHOW_ADD_MODAL";
export const EDITIONS_HIDE_ADD_MODAL = "@editions/EDITIONS_HIDE_ADD_MODAL";
export const EDITIONS_SHOW_EDIT_MODAL = "@editions/SHOW_EDIT_MODAL";
export const EDITIONS_HIDE_EDIT_MODAL = "@editions/EDITIONS_HIDE_EDIT_MODAL";
export const EDITIONS_SHOW_DELETE_MODAL = "@editions/SHOW_DELETE_MODAL";
export const EDITIONS_HIDE_DELETE_MODAL =
  "@editions/EDITIONS_HIDE_DELETE_MODAL";

export const SET_SELECTED_EDITION = "@editions/SET_SELECTED_EDITION";

export const EDITIONS_FILTER_INIT = "@editions/EDITIONS_FILTER_INIT";
export const EDITIONS_FILTER_SUCCESS = "@editions/EDITIONS_FILTER_SUCCESS";
export const EDITIONS_FILTER_FAILURE = "@editions/EDITIONS_FILTER_FAILURE";

export const IMPORT_EDITIONS_INIT = "@editions/IMPORT_EDITIONS_INIT";
export const IMPORT_EDITIONS_SUCCESS = "@editions/IMPORT_EDITIONS_SUCCESS";
export const IMPORT_EDITIONS_FAILURE = "@editions/IMPORT_EDITIONS_FAILURE";
