export const INITIAL_LOAD_INIT = '@orders/INITIAL_LOAD_INIT';
export const INITIAL_LOAD_SUCCESS = '@orders/INITIAL_LOAD_SUCCESS';
export const INITIAL_LOAD_FAILURE = '@orders/INITIAL_LOAD_FAILURE';

export const FILTER_ORDERS_INIT = '@orders/FILTER_ORDERS_INIT';
export const FILTER_ORDERS_SUCCESS = '@orders/FILTER_ORDERS_SUCCESS';
export const FILTER_ORDERS_FAILURE = '@orders/FILTER_ORDERS_FAILURE';

export const SHOW_ADD_MODAL = '@orders/SHOW_ADD_MODAL';
export const SHOW_EDIT_MODAL = '@orders/SHOW_EDIT_MODAL';
export const SHOW_DELETE_MODAL = '@orders/SHOW_DELETE_MODAL';

export const ADD_ORDER_INIT = '@orders/ADD_ORDER_INIT';
export const ADD_ORDER_SUCCESS = '@orders/ADD_ORDER_SUCCESS';
export const ADD_ORDER_FAILURE = '@orders/ADD_ORDER_FAILURE';

export const EDIT_ORDER_INIT = '@orders/EDIT_ORDER_INIT';
export const EDIT_ORDER_SUCCESS = '@orders/EDIT_ORDER_SUCCESS';
export const EDIT_ORDER_FAILURE = '@orders/EDIT_ORDER_FAILURE';

export const DELETE_ORDER_INIT = '@orders/DELETE_ORDER_INIT';
export const DELETE_ORDER_SUCCESS = '@orders/DELETE_ORDER_SUCCESS';
export const DELETE_ORDER_FAILURE = '@orders/DELETE_ORDER_FAILURE';

export const GET_ALL_PRODUCTEDITIONS_INIT =
  '@orders/GET_ALL_PRODUCTEDITIONS_INIT';
export const GET_ALL_PRODUCTEDITIONS_SUCESS =
  '@orders/GET_ALL_PRODUCTEDITIONS_SUCESS';
export const GET_ALL_PRODUCTEDITIONS_FAILURE =
  '@orders/GET_ALL_PRODUCTEDITIONS_FAILURE';

export const GETEDITIONSFILTER_INIT = '@orders/GETEDITIONSFILTER_INIT';
export const GETEDITIONSFILTER_SUCCESS = '@orders/GETEDITIONSFILTER_SUCCESS';
export const GETEDITIONSFILTER_FAILURE = '@orders/GETEDITIONSFILTER_FAILURE';

export const GETEDITIONSFOROP_INIT = '@orders/GETEDITIONSFOROP_INIT';
export const GETEDITIONSFOROP_SUCCESS = '@orders/GETEDITIONSFOROP_SUCCESS';
export const GETEDITIONSFOROP_FAILURE = '@orders/GETEDITIONSFOROP_FAILURE';

export const GET_CLIENTSWITHBALANCE_INIT =
  '@orders/GET_CLIENTSWITHBALANCE_INIT';
export const GET_CLIENTSWITHBALANCE_SUCESS =
  '@orders/GET_CLIENTSWITHBALANCE_SUCESS';
export const GET_CLIENTSWITHBALANCE_FAILURE =
  '@orders/GET_CLIENTSWITHBALANCE_FAILURE';

export const GET_ALL_CONTRACTS_INIT = '@orders/GET_ALL_CONTRACTS_INIT';
export const GET_ALL_CONTRACTS_SUCESS = '@orders/GET_ALL_CONTRACTS_SUCESS';
export const GET_ALL_CONTRACTS_FAILURE = '@orders/GET_ALL_CONTRACTS_FAILURE';

export const GET_ALL_SPACESTYPES_INIT = '@orders/GET_ALL_SPACESTYPES_INIT';
export const GET_ALL_SPACETYPES_SUCESS = '@orders/GET_ALL_SPACETYPES_SUCESS';
export const GET_ALL_SPACETYPES_FAILURE = '@orders/GET_ALL_SPACETYPES_FAILURE';

export const GET_ALL_SPACELOCATIONS_INIT =
  '@orders/GET_ALL_SPACELOCATIONS_INIT';
export const GET_ALL_SPACELOCATIONS_SUCESS =
  '@orders/GET_ALL_SPACELOCATIONS_SUCESS';
export const GET_ALL_SPACELOCATIONS_FAILURE =
  '@orders/GET_ALL_SPACELOCATIONS_FAILURE';
