export const INITIAL_LOAD_INIT = "@clients/INITIAL_LOAD_INIT";
export const INITIAL_LOAD_SUCCESS = "@clients/INITIAL_LOAD_SUCCESS";
export const INITIAL_LOAD_FAILURE = "@clients/INITIAL_LOAD_FAILURE";

export const SEARCH_CLIENTS_INIT = "@clients/SEARCH_CLIENTS_INIT";
export const SEARCH_CLIENTS_SUCCESS = "@clients/SEARCH_CLIENTS_SUCCESS";
export const SEARCH_CLIENTS_FAILURE = "@clients/SEARCH_CLIENTS_FAILURE";

export const GET_TAXES_INIT = "@clients/GET_TAXES_INIT";
export const GET_TAXES_SUCCESS = "@clients/GET_TAXES_SUCCESS";
export const GET_TAXES_FAILURE = "@clients/GET_TAXES_FAILURE";

export const SHOW_ADD_MODAL = "@clients/SHOW_ADD_MODAL";
export const SHOW_EDIT_MODAL = "@clients/SHOW_EDIT_MODAL";
export const SHOW_DELETE_MODAL = "@clients/SHOW_DELETE_MODAL";

export const ADD_CLIENT_INIT = "@clients/ADD_CLIENT_INIT";
export const ADD_CLIENT_SUCCESS = "@clients/ADD_CLIENT_SUCCESS";
export const ADD_CLIENT_FAILURE = "@clients/ADD_CLIENT_FAILURE";

export const EDIT_CLIENT_INIT = "@clients/EDIT_CLIENT_INIT";
export const EDIT_CLIENT_SUCCESS = "@clients/EDIT_CLIENT_SUCCESS";
export const EDIT_CLIENT_FAILURE = "@clients/EDIT_CLIENT_FAILURE";

export const DELETE_CLIENT_INIT = "@clients/DELETE_CLIENT_INIT";
export const DELETE_CLIENT_SUCCESS = "@clients/DELETE_CLIENT_SUCCESS";
export const DELETE_CLIENT_FAILURE = "@clients/DELETE_CLIENT_FAILURE";

export const FILTER_CLIENTS_INIT = "@clients/FILTER_CLIENTS_INIT";
export const FILTER_CLIENTS_SUCCESS = "@clients/FILTER_CLIENTS_SUCCESS";
export const FILTER_CLIENTS_FAILURE = "@clients/FILTER_CLIENTS_FAILURE";

export const GET_LOCATION_DATA_INIT = "@clients/GET_LOCATION_DATA_INIT";
export const GET_LOCATION_DATA_SUCCESS = "@clients/GET_LOCATION_DATA_SUCCESS";
export const GET_LOCATION_DATA_FAILURE = "@clients/GET_LOCATION_DATA_FAILURE";

export const GET_ALL_COUNTRIES_INIT = "@clients/GET_ALL_COUNTRIES_INIT";
export const GET_ALL_COUNTRIES_SUCCESS = "@clients/GET_ALL_COUNTRIES_SUCCESS";
export const GET_ALL_COUNTRIES_FAILURE = "@clients/GET_ALL_COUNTRIES_FAILURE";

export const GET_ALL_STATES_INIT = "@clients/GET_ALL_STATES_INIT";
export const GET_ALL_STATES_SUCCESS = "@clients/GET_ALL_STATES_SUCCESS";
export const GET_ALL_STATES_FAILURE = "@clients/GET_ALL_STATES_FAILURE";

export const GET_ALL_DISTRICTS_INIT = "@clients/GET_ALL_DISTRICTS_INIT";
export const GET_ALL_DISTRICTS_SUCCESS = "@clients/GET_ALL_DISTRICTS_SUCCESS";
export const GET_ALL_DISTRICTS_FAILURE = "@clients/GET_ALL_DISTRICTS_FAILURE";

export const GET_ALL_CITIES_INIT = "@clients/GET_ALL_CITIES_INIT";
export const GET_ALL_CITIES_SUCCESS = "@clients/GET_ALL_CITIES_SUCCESS";
export const GET_ALL_CITIES_FAILURE = "@clients/GET_ALL_CITIES_FAILURE";

export const GET_ALL_TAX_CATEGORIES_INIT =
  "@clients/GET_ALL_TAX_CATEGORIES_INIT";
export const GET_ALL_TAX_CATEGORIES_SUCCESS =
  "@clients/GET_ALL_TAX_CATEGORIES_SUCCESS";
export const GET_ALL_TAX_CATEGORIES_FAILURE =
  "@clients/GET_ALL_TAX_CATEGORIES_FAILURE";
