export const INITIAL_LOAD_INIT = '@currency/INITIAL_LOAD_INIT';
export const INITIAL_LOAD_SUCCESS = '@currency/INITIAL_LOAD_SUCCESS';
export const INITIAL_LOAD_FAILURE = '@currency/INITIAL_LOAD_FAILURE';

export const GETCURRENCIES_INIT = '@currency/GETCURRENCIES_INIT';
export const GETCURRENCIES_SUCCESS = '@currency/GETCURRENCIES_SUCCESS';
export const GETCURRENCIES_FAILURE = '@currency/GETCURRENCIES_FAILURE';

export const ADDCURRENCY_INIT = '@currency/ADDCURRENCY_INIT';
export const ADDCURRENCY_SUCCESS = '@currency/ADDCURRENCY_SUCCESS';
export const ADDCURRENCY_FAILURE = '@currency/ADDCURRENCY_FAILURE';

export const EDITCURRENCY_INIT = '@currency/EDITCURRENCY_INIT';
export const EDITCURRENCY_SUCCESS = '@currency/EDITCURRENCY_SUCCESS';
export const EDITCURRENCY_FAILURE = '@currency/EDITCURRENCY_FAILURE';

export const DELETECURRENCY_INIT = '@currency/DELETECURRENCY_INIT';
export const DELETECURRENCY_SUCCESS = '@currency/DELETECURRENCY_SUCCESS';
export const DELETECURRENCY_FAILURE = '@currency/DELETECURRENCY_FAILURE';

export const SHOW_ADD_MODAL = '@currency/SHOW_ADD_MODAL';
export const SHOW_EDIT_MODAL = '@currency/SHOW_EDIT_MODAL';
export const SHOW_DELETE_MODAL = '@currency/SHOW_DELETE_MODAL';
