export const INITIAL_LOAD_INIT = "@euroParity/INITIAL_LOAD_INIT";
export const INITIAL_LOAD_SUCCESS = "@euroParity/INITIAL_LOAD_SUCCESS";
export const INITIAL_LOAD_FAILURE = "@euroParity/INITIAL_LOAD_FAILURE";

export const GETEUROPARITIES_INIT = "@europarity/GETEUROPARITIES_INIT";
export const GETEUROPARITIES_SUCCESS = "@europarity/GETEUROPARITIES_SUCCESS";
export const GETEUROPARITIES_FAILURE = "@europarity/GETEUROPARITIES_FAILURE";

export const ADDEUROPARITY_INIT = "@euroParity/ADDEUROPARITY_INIT";
export const ADDEUROPARITY_SUCCESS = "@euroParity/ADDEUROPARITY_SUCCESS";
export const ADDEUROPARITY_FAILURE = "@euroParity/ADDEUROPARITY_FAILURE";

export const DELETEEUROPARITY_INIT = "@euroParity/DELETEEUROPARITY_INIT";
export const DELETEEUROPARITY_SUCCESS = "@euroParity/DELETEEUROPARITY_SUCCESS";
export const DELETEEUROPARITY_FAILURE = "@euroParity/DELETEEUROPARITY_FAILURE";

export const SHOW_ADD_MODAL = "@euroParity/SHOW_ADD_MODAL";
export const SHOW_DELETE_MODAL = "@euroParity/SHOW_DELETE_MODAL";
