/* API Data */
export const GET_ALL_API_DATA_INIT = "@init/GET_ALL_API_DATA_INIT";
export const GET_ALL_API_DATA_SUCCESS = "@init/GET_ALL_API_DATA_SUCCESS";
export const GET_ALL_API_DATA_FAILURE = "@init/GET_ALL_API_DATA_FAILURE";

export const GET_ALL_COUNTRIES_INIT = "@apiData/GET_ALL_COUNTRIES_INIT";
export const GET_ALL_COUNTRIES_SUCCESS = "@apiData/GET_ALL_COUNTRIES_SUCCESS";
export const GET_ALL_COUNTRIES_FAILURE = "@apiData/GET_ALL_COUNTRIES_FAILURE";

export const GET_ALL_STATES_INIT = "@apiData/GET_ALL_STATES_INIT";
export const GET_ALL_STATES_SUCCESS = "@apiData/GET_ALL_STATES_SUCCESS";
export const GET_ALL_STATES_FAILURE = "@apiData/GET_ALL_STATES_FAILURE";

export const GET_ALL_DISTRICTS_INIT = "@apiData/GET_ALL_DISTRICTS_INIT";
export const GET_ALL_DISTRICTS_SUCCESS = "@apiData/GET_ALL_DISTRICTS_SUCCESS";
export const GET_ALL_DISTRICTS_FAILURE = "@apiData/GET_ALL_DISTRICTS_FAILURE";

export const GET_ALL_CITIES_INIT = "@apiData/GET_ALL_CITIES_INIT";
export const GET_ALL_CITIES_SUCCESS = "@apiData/GET_ALL_CITIES_SUCCESS";
export const GET_ALL_CITIES_FAILURE = "@apiData/GET_ALL_CITIES_FAILURE";

export const GET_ALL_APP_ROLES_INIT = "@apiData/GET_ALL_APP_ROLES_INIT";
export const GET_ALL_APP_ROLES_SUCCESS = "@apiData/GET_ALL_APP_ROLES_SUCCESS";
export const GET_ALL_APP_ROLES_FAILURE = "@apiData/GET_ALL_APP_ROLES_FAILURE";
